# Generated by Django 4.1.2 on 2022-10-11 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255, verbose_name='Görev Başlık')),
                ('project_name', models.CharField(blank=True, max_length=255, verbose_name='Proje Adı')),
                ('deadline', models.DateTimeField(verbose_name='Tarih')),
                ('task_description', models.TextField(verbose_name='Görev Açıklamaları')),
                ('status', models.IntegerField(choices=[(0, 'Taslak'), (1, 'Yayınla'), (2, 'Arşiv')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
