# Generated by Django 4.1.2 on 2022-10-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mygroup',
            field=models.CharField(choices=[('Arge', 'Arge'), ('Muhasebe', 'Muhasebe'), ('Satın Alma', 'Satın Alma'), ('Üretim', 'Üretim'), ('Planlama', 'Planlama')], max_length=50),
        ),
    ]
